### ISSUE TITLE
Run image in docker.io causing rate limit issue

### ISSUE THREAD

**Issue by ryneal** [paketo-buildpacks/base-builder#165]
## What happened?
Hitting rate limits from docker.io using buildpack

* What were you attempting to do?
Run buildpack very frequently

* What did you expect to happen?
No rate limits hit

* What was the actual behavior? Please provide log output, if possible.
Because the run image is set to `"index.docker.io/paketobuildpacks/run:base-cnb"` it is causing an error in my pipelines, because of the frequency it is being used.

Logs included:
```
ERROR: failed to build: fetching lifecycle image: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Gitlab with CNB
* What buildpacks are you using? paketobuildpacks/builder:0.1.83-base

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`? paketobuildpacks/builder:0.1.83-base

## Checklist
* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by fg-j** [comment]
Hey @ryneal thanks for bringing this to our attention. I'll investigate what we might do to improve this experience for Dockerhub users.

In the meantime, if your pipelines are using `pack` to run builds, you can [`pack build`](https://buildpacks.io/docs/tools/pack/cli/pack_build/) with `--run-image=gcr.io/paketo-buildpacks/run:base-cnb` to take advantage of GCR's less-restrictive rate limiting, since we also publish that run image to GCR.

**Comment by ryneal** [comment]
Thank you for your response and suggestion, I've applied this change as a workaround, and will feedback if I get any more issues

**Comment by fg-j** [comment]
I'll close this for now. Feel free to reopen if you start seeing issues with the workaround.
