### ISSUE TITLE
Add support for curl

### ISSUE THREAD

**Issue by goafabric** [paketo-buildpacks/base-builder#234]
I am using paketo build packs with Spring Boot for Native Container Images.
While it works in general, there is a requirement for Docker to have access to either curl or wget inside the base image.
Unfortunately neiter :tiny nor :base supports this.
And we have to use :full which is 700MB big.

So it would be nice that at least :base contains curl out of the box

**Comment by ryanmoran** [comment]
Can you explain a bit more about this requirement? Why does Docker need `curl` or `wget`?

**Comment by goafabric** [comment]
@ryanmoran 
A sorry forgot about that ... 
It's usually needed for having healtchecks.
While in Kubernetes we can leverage things like initcontainers,
there is no equivalent for Docker(Compose) so the base images always need to have access to curl and wget.

**Comment by fg-j** [comment]
@goafabric -- trying to understand more about your use case. 

1. Are you saying that you need the image that comes out of the buildpack build to have `curl` so that the container can check some other service's health by hitting a certain endpoint? Or something different?

2. How are init containers helping you solve your problem on kubernetes?

**Comment by goafabric** [comment]
1.
Honestly .. it's a standard usecase for docker containers, that the baseimage contains curl,
so that we can define a healtcheck like this:
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 10s

2.
IN Kubernetes this is not needed, because initcontainers allows for healthchecks with additional containers,
so no need to put it in the baseimage .. nontheless a solution for both scenarios (docker + kubernetes) is needed

**Comment by goafabric** [comment]
@fg-j 
Thanks for taking it into consideration.
As i can understand the concerns somehow, i cannot understand it completely.
Our goal is pretty simple, building spring boot containers with native binaries.
With JVM binaries we just use as adoptopenjdk debian base image, which automatically includes curl.
For quarkus, they automatically create images, also with curl.
Also the Paketo Full Image has curl inside .. so why are there no concerns ?

The full image is just too big with about 700MBs.

**Comment by goafabric** [comment]
@dmikusa-pivotal thx for the complete explanation, i will close the ticket now

**Comment by tylerbenson** [comment]
I think this is a relevant discussion that warrants better consideration.  What is the recommended method for defining a healthcheck for something like a spring boot app?  Would `nc` be an option to add to allow testing if a port is open (eg `nc -zv localhost 8080`) or does it have a similar number of additional dependencies?

**Comment by dmikusa-pivotal** [comment]
@tylerbenson - `nc` might be smaller, I didn't do a comparison, but it is probably worse from a security standpoint. Because you can use `nc` to listen for incoming connections, it is very helpful for an attacker.

For Spring Boot Actuators, I think the recommendation would be to use an [HTTP probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request). That doesn't require any tools in the container, however, that only works with K8s.

The problem here is really only specific to Docker or other container runtimes where there is no HTTP-based probe available. I think that's my other reservation on this, it's hard to add something to the image for *everyone* when it's only needed by a segment of the users.

**Comment by tylerbenson** [comment]
I decided to create my own main class that can check if a port is bound.

```java
import java.io.IOException;
import java.net.Socket;

/**
 * Used by Docker Compose healthcheck to verify if a particular port is bound and ready to accept requests.
 */
public class PortBoundCheck {
    private static String USAGE = "Usage: java -cp ./path/to/classpath " + PortBoundCheck.class.getName() + " [port]";

    public static void main(String[] args) {
        if (args.length != 1 || "0".equals(args[0])) {
            System.err.println(USAGE);
            System.exit(1);
            return;
        }
        int port;
        try {
            port = Integer.parseInt(args[0]);
        } catch (NumberFormatException ex) {
            ex.printStackTrace();
            System.err.println(USAGE);
            System.exit(2);
            return;
        }

        try (Socket s = new Socket((String) null, port)) { // always checking localhost.
            // No exception means...
            System.out.println("Port " + port + " is bound.");
            System.exit(0);
        } catch (IOException e) {
            System.err.println("Port " + port + " is NOT bound.");
            System.exit(3);
        }
    }
}
```

I then can call it with a healthcheck. 
```yml
    healthcheck:
      test:
        - CMD
        - /layers/paketo-buildpacks_amazon-corretto/jdk/bin/java
        - -cp
        - /workspace/BOOT-INF/classes/
        - PortBoundCheck
        - "8080"
```

**Comment by dmikusa-pivotal** [comment]
Awesome, & thanks for sharing
