### ISSUE TITLE
Source with node_modules fails to detect Java application

### ISSUE THREAD

**Issue by dsyer** [paketo-buildpacks/base-builder#341]
If you are building a Java application with Maven or Gradle, and front end resources are built using Node.js as part of the Java build process, you don't want the buildpack to think you are a Node.js application. Sample code example: https://github.com/dsyer/spring-boot-angular or https://github.com/dsyer/spring-boot-js-demo/tree/main/nodejs. Example output from one of those samples:

```
$ pack build dsyer/nodejs
...
===> DETECTING
5 of 10 buildpacks participating
paketo-buildpacks/ca-certificates 3.0.1
paketo-buildpacks/node-engine     0.11.2
paketo-buildpacks/npm-install     0.6.2
paketo-buildpacks/node-module-bom 0.2.0
paketo-buildpacks/npm-start       0.6.1
...
```

There's a workaround, which is to set `BP_NODE_PROJECT_PATH` to a directory that doesn't have any node content. E.g. 

```
$ pack --env BP_NODE_PROJECT_PATH=target build dsyer/nodejs
...
===> DETECTING
8 of 19 buildpacks participating
paketo-buildpacks/ca-certificates   3.0.1
paketo-buildpacks/bellsoft-liberica 9.0.1
paketo-buildpacks/syft              1.3.0
paketo-buildpacks/maven             6.0.1
paketo-buildpacks/executable-jar    6.0.1
paketo-buildpacks/apache-tomcat     7.0.2
paketo-buildpacks/dist-zip          5.0.1
paketo-buildpacks/spring-boot       5.2.0
===> RESTORING
...
```

**Comment by dmikusa-pivotal** [comment]
@paketo-buildpacks/builders-maintainers - Hi, I moved this over here. We're having some trouble building Java apps that also contain Javascript frontends. 

The builder (I think this applies for full as well) has Node.js before Java, so when the build happens, it sees our frontend code and attempts to build a Node.js app. The intent is to have this build as a Java application.

Would it be possible to swap the order so that Node.js is lower in the order group. It seems like a common problem (not just Java) where apps bundle both backend and frontend code. If we put Javascript at the end of the order group it should make this work better across all language families. Or is there a particular reason we have it in the present order?

Thanks!

**Comment by fg-j** [comment]
Hey @dmikusa-pivotal. The current order was established in [this RFC](https://github.com/paketo-buildpacks/rfcs/blob/009ff161f7b4f05c354766eb89e0a218eef5e929/text/builders/0001-buildpack-order.md) and cites prior experiences with Cloud Foundry buildpacks in its explanation for the provided order. I think we'd need to write an RFC amending the order. As an initial proof of concept, I re-ordered the builder [on a branch](https://github.com/paketo-buildpacks/base-builder/tree/reorder-base). In the update order, NodeJS comes after most other language families, and the smoke tests still pass, which somewhat validates the proposed reordering.

**Comment by dmikusa-pivotal** [comment]
✅  I'll write up an RFC to propose the change. Thanks
